# Generated by Django 4.2.4 on 2023-09-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easystock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='valor',
            field=models.FloatField(max_length=255),
        ),
    ]
