# Generated by Django 4.2.4 on 2023-09-02 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easystock', '0002_alter_produto_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easystock.produto')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easystock.tipo')),
            ],
        ),
    ]
