# Generated by Django 4.2.4 on 2023-09-02 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easystock', '0003_classificacao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classificacao',
            new_name='Classificacoes',
        ),
    ]
