# Generated by Django 4.2.4 on 2023-09-02 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easystock', '0004_rename_classificacao_classificacoes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classificacoes',
            new_name='Classificacoe',
        ),
    ]
